# 4 MUESTREO

### 4.1 Muestreo Estadístico

### $\bf{Población:}$ conjunto de sujetos/objetos con una o varias características que podemos medir. $\newline$

### $\bf{Muestra:}$ subconjunto de una población.

### Cuando la selección de una muestra de la población se realiza de manera que todas las muestras del mismo tamaño sean equiprobables, se denomina $\bf{muestreo}$ $\bf{aleaorio}$.

### Consideremos una urna de 100 bolas numeradas del 1 al 100:

<img src="urna.png">

### Suponga que se requiere una muestra aleatoria con reposición/reemplazamiento/repetición de tamaño 16.

<img src="urna2.png">

Para generar la muestra aleatoria en python usaremos la función $\bf{random.choices}$ del módulo $\bf{random}$.

In [6]:
import random

esferas = list(range(1, 101))
muestra = random.choices(esferas, k=15)
muestra

[21, 66, 80, 68, 17, 73, 37, 42, 97, 14, 82, 46, 63, 39, 12]

Para el siguiente ejemplo usaremos una base de datos denominada iris, la cual importamos usando $\textbf{Seaborn}$. La tabla de datos iris contiene 150 flores de 3 especies diferentes: setosa, versicolor y virginica.

In [1]:
import seaborn as sns
iris = sns.load_dataset('iris')

In [2]:
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

### Si quisiéramos una muestra de 20 flores con reposición, haríamos lo siguiente:

In [3]:
muestra1 = iris.sample(20, replace=True) #aquí si repetición
muestra1

     sepal_length  sepal_width  petal_length  petal_width     species
120           6.9          3.2           5.7          2.3   virginica
50            7.0          3.2           4.7          1.4  versicolor
13            4.3          3.0           1.1          0.1      setosa
73            6.1          2.8           4.7          1.2  versicolor
127           6.1          3.0           4.9          1.8   virginica
27            5.2          3.5           1.5          0.2      setosa
110           6.5          3.2           5.1          2.0   virginica
136           6.3          3.4           5.6          2.4   virginica
75            6.6          3.0           4.4          1.4  versicolor
49            5.0          3.3           1.4          0.2      setosa
97            6.2          2.9           4.3          1.3  versicolor
58            6.6          2.9           4.6          1.3  versicolor
1             4.9          3.0           1.4          0.2      setosa
80            5.5          2.4           3.8          1.1  versicolor
113           5.7          2.5           5.0          2.0   virginica
143           6.8          3.2           5.9          2.3   virginica
101           5.8          2.7           5.1          1.9   virginica
88            5.6          3.0           4.1          1.3  versicolor
15            5.7          4.4           1.5          0.4      setosa
18            5.7          3.8           1.7          0.3      setosa

### Otra manera de extraer nuestra muestra sería repetir 15 veces el proceso de sacar una bola de la urna pero ahora sin devolverla. En este caso se habla de una $\bf{muestra}$ $\bf{aleatoria}$ $\bf{sin}$ $\bf{reposición}$.

### Para obtener una muestra de 10 flores sin reposición, haríamos los pasos siguientes:

In [4]:
muestra2= iris.sample(10, replace=False) #sin repetición
muestra2

     sepal_length  sepal_width  petal_length  petal_width     species
115           6.4          3.2           5.3          2.3   virginica
1             4.9          3.0           1.4          0.2      setosa
103           6.3          2.9           5.6          1.8   virginica
149           5.9          3.0           5.1          1.8   virginica
29            4.7          3.2           1.6          0.2      setosa
88            5.6          3.0           4.1          1.3  versicolor
62            6.0          2.2           4.0          1.0  versicolor
126           6.2          2.8           4.8          1.8   virginica
63            6.1          2.9           4.7          1.4  versicolor
15            5.7          4.4           1.5          0.4      setosa

### Supongamos que los individuos de una población vienen dados en forma de una lista ordenada. El $\bf{muestreo}$ $\bf{sistemático}$ consiste en tomarlos a intervalos constantes escogiendo al azar el primer individuo que elegimos.

<img src="urna3.png">

### Ahora calculemos una muestra aleatoria sistemática de la tabla de datos iris de tamaño 10.

In [8]:
import numpy as np 

primera_flor = random.randint(0, 151)
incremento = 15

flores_elegidas = np.arange(primera_flor, primera_flor + incremento * 10, incremento)
print(flores_elegidas)

flores_elegidas_sis=flores_elegidas%150
print(flores_elegidas_sis)

[ 33  48  63  78  93 108 123 138 153 168]
[ 33  48  63  78  93 108 123 138   3  18]

In [10]:
muestra3=iris.iloc[flores_elegidas_sis]
muestra3

     sepal_length  sepal_width  petal_length  petal_width     species
33            5.5          4.2           1.4          0.2      setosa
48            5.3          3.7           1.5          0.2      setosa
63            6.1          2.9           4.7          1.4  versicolor
78            6.0          2.9           4.5          1.5  versicolor
93            5.0          2.3           3.3          1.0  versicolor
108           6.7          2.5           5.8          1.8   virginica
123           6.3          2.7           4.9          1.8   virginica
138           6.0          3.0           4.8          1.8   virginica
3             4.6          3.1           1.5          0.2      setosa
18            5.7          3.8           1.7          0.3      setosa

### Cuando la población está clasificada en estratos (grupos), se toma una muestra aleatoria de cada estrato y se unen en una muestra global. A este proceso se le llama $\bf{muestreo}$ $\bf{aleatorio}$ $\bf{estratificado}$.

<img src="urna4.png">

### En el caso de la tabla de datos iris está estratificada en tres grupos: setosa, versicolor y virginica. Cada estrato está compuesto por 50 flores de la misma especie. Vamos a hallar una muestra de tamaño 12 hallando tres muestras de tamaño 4 de cada especie (estrato) con reposición y después juntaremos la tres submuestras para obtener la muestra global.

In [11]:
 iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [12]:
iris['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [13]:
setosa=iris.query('species == "setosa"')
setosa.describe()

       sepal_length  sepal_width  petal_length  petal_width
count      50.00000    50.000000     50.000000    50.000000
mean        5.00600     3.428000      1.462000     0.246000
std         0.35249     0.379064      0.173664     0.105386
min         4.30000     2.300000      1.000000     0.100000
25%         4.80000     3.200000      1.400000     0.200000
50%         5.00000     3.400000      1.500000     0.200000
75%         5.20000     3.675000      1.575000     0.300000
max         5.80000     4.400000      1.900000     0.600000

In [15]:
versicolor=iris.query('species == "versicolor"')
versicolor

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
53           5.5          2.3           4.0          1.3  versicolor
54           6.5          2.8           4.6          1.5  versicolor
55           5.7          2.8           4.5          1.3  versicolor
56           6.3          3.3           4.7          1.6  versicolor
57           4.9          2.4           3.3          1.0  versicolor
58           6.6          2.9           4.6          1.3  versicolor
59           5.2          2.7           3.9          1.4  versicolor
60           5.0          2.0           3.5          1.0  versicolor
61           5.9          3.0           4.2          1.5  versicolor
62           6.0          2.2           4.0          1.0  versicolor
63           6.1          2.9           4.7          1.4  versicolor
64           5.6          2.9           3.6          1.3  versicolor
65           6.7          3.1           4.4          1.4  versicolor
66           5.6          3.0           4.5          1.5  versicolor
67           5.8          2.7           4.1          1.0  versicolor
68           6.2          2.2           4.5          1.5  versicolor
69           5.6          2.5           3.9          1.1  versicolor
70           5.9          3.2           4.8          1.8  versicolor
71           6.1          2.8           4.0          1.3  versicolor
72           6.3          2.5           4.9          1.5  versicolor
73           6.1          2.8           4.7          1.2  versicolor
74           6.4          2.9           4.3          1.3  versicolor
75           6.6          3.0           4.4          1.4  versicolor
76           6.8          2.8           4.8          1.4  versicolor
77           6.7          3.0           5.0          1.7  versicolor
78           6.0          2.9           4.5          1.5  versicolor
79           5.7          2.6           3.5          1.0  versicolor
80           5.5          2.4           3.8          1.1  versicolor
81           5.5          2.4           3.7          1.0  versicolor
82           5.8          2.7           3.9          1.2  versicolor
83           6.0          2.7           5.1          1.6  versicolor
84           5.4          3.0           4.5          1.5  versicolor
85           6.0          3.4           4.5          1.6  versicolor
86           6.7          3.1           4.7          1.5  versicolor
87           6.3          2.3           4.4          1.3  versicolor
88           5.6          3.0           4.1          1.3  versicolor
89           5.5          2.5           4.0          1.3  versicolor
90           5.5          2.6           4.4          1.2  versicolor
91           6.1          3.0           4.6          1.4  versicolor
92           5.8          2.6           4.0          1.2  versicolor
93           5.0          2.3           3.3          1.0  versicolor
94           5.6          2.7           4.2          1.3  versicolor
95           5.7          3.0           4.2          1.2  versicolor
96           5.7          2.9           4.2          1.3  versicolor
97           6.2          2.9           4.3          1.3  versicolor
98           5.1          2.5           3.0          1.1  versicolor
99           5.7          2.8           4.1          1.3  versicolor

In [16]:
virginica=iris.query('species == "virginica"')

In [17]:
muestra_setosa = setosa.sample(4, replace=True)
muestra_versicolor = versicolor.sample(4, replace=True)
muestra_virginica = virginica.sample(4, replace=True)

In [18]:
muestra_setosa

    sepal_length  sepal_width  petal_length  petal_width species
17           5.1          3.5           1.4          0.3  setosa
37           4.9          3.6           1.4          0.1  setosa
11           4.8          3.4           1.6          0.2  setosa
27           5.2          3.5           1.5          0.2  setosa

In [19]:
import pandas as pd
muestra4=pd.concat([muestra_setosa, muestra_versicolor, muestra_virginica])
muestra4

     sepal_length  sepal_width  petal_length  petal_width     species
17            5.1          3.5           1.4          0.3      setosa
37            4.9          3.6           1.4          0.1      setosa
11            4.8          3.4           1.6          0.2      setosa
27            5.2          3.5           1.5          0.2      setosa
71            6.1          2.8           4.0          1.3  versicolor
89            5.5          2.5           4.0          1.3  versicolor
80            5.5          2.4           3.8          1.1  versicolor
75            6.6          3.0           4.4          1.4  versicolor
125           7.2          3.2           6.0          1.8   virginica
140           6.7          3.1           5.6          2.4   virginica
134           6.1          2.6           5.6          1.4   virginica
148           6.2          3.4           5.4          2.3   virginica

In [21]:
muestra5=muestra4.sample(frac=1).reset_index(drop=True) #frac=1 la fracción 1, que es en si toda la muestra
muestra5

    sepal_length  sepal_width  petal_length  petal_width     species
0            5.5          2.4           3.8          1.1  versicolor
1            6.2          3.4           5.4          2.3   virginica
2            5.1          3.5           1.4          0.3      setosa
3            6.1          2.8           4.0          1.3  versicolor
4            6.6          3.0           4.4          1.4  versicolor
5            5.2          3.5           1.5          0.2      setosa
6            4.9          3.6           1.4          0.1      setosa
7            7.2          3.2           6.0          1.8   virginica
8            6.1          2.6           5.6          1.4   virginica
9            5.5          2.5           4.0          1.3  versicolor
10           4.8          3.4           1.6          0.2      setosa
11           6.7          3.1           5.6          2.4   virginica

In [22]:
muestra5.to_csv('muestra5.csv', index=False)

### $\textbf{Ejercicio}$ De la base de datos "titanic" de la biblioteca seaborn, generar una muestra aleatoria sin remplazo, otra con remplazo, una sistemática, y finalmente una estratificada considerando la variable "sex".

In [23]:
titanic = sns.load_dataset('titanic')

In [24]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True