<h2>Handling Categorical Variables</h2>
<div style="text-align: justify">
Categorical variables are used to represent groups or categories that are qualitative in nature. Some examples are survey responses like marital status, profession or educational qualifications. While these can easily be understood by a human, some problems can arise with categorical data and they must be dealt with before proceeding with any other task.
To get from qualitative inputs to quantitative features, one may naively think that assigning every category in a column a number would suffice, but categories are unordered, so assigning this order may greatly penalize the effectiveness of your model.

<h2>Encoding categorical features</h2>
Certain learning algorithms like regression and neural networks require their input to be numbers. Hence, categorical data must be converted to numbers to use these algorithms.<br>
<h3>One-hot encoding</h3>
One-hot encoding converts n categories into n features. You can use the get_dummies() function to one-hot encode columns. The function takes a DataFrame and a list of categorical columns you want converted into one hot encoded columns, and returns an updated DataFrame with these columns included.

<h3>Dummy encoding</h3>
Dummy encoding creates n-1 features for n categories, omitting the first category. For dummy encoding, you can use the same get_dummies() function with an additional argument, drop_first set to True.<br>
Both these methods have different advantages. One-hot encoding generally creates much more explainable features, but one must be aware that one hot encoding may create features that are entirely collinear due to the same information being represented multiple times.<br>
Both one-hot encoding and dummy encoding may result in a huge number of columns being created if there are too many different categories in a column. In these cases, you may want to only create columns for the most common values. You can check the number of occurrences of different features in a column using the value_counts() method on a specific column.
</div>

In [ ]:
import pandas as pd
# one hot encoding
data=pd.DataFrame({"country":["Mexico","USA","Canada","USA"],"gender":["F","F","M","M"]})
display(data)
display(pd.get_dummies(data,columns=["country","gender"],prefix=["c","g"],dtype=int))
display(pd.get_dummies(data,columns=["country"],prefix=["c"]))
#dummy enconding
display(pd.get_dummies(data,columns=["country", 'gender'],prefix=["c", 'g'],dtype=int, drop_first=True))

  country gender
0  Mexico      F
1     USA      F
2  Canada      M
3     USA      M

   c_Canada  c_Mexico  c_USA  g_F  g_M
0         0         1      0    1    0
1         0         0      1    1    0
2         1         0      0    0    1
3         0         0      1    0    1

  gender  c_Canada  c_Mexico  c_USA
0      F     False      True  False
1      F     False     False   True
2      M      True     False  False
3      M     False     False   True

   c_Mexico  c_USA  g_M
0         1      0    0
1         0      1    0
2         0      0    1
3         0      1    1

In [ ]:
#activity:. apply one encoding for departmente/jod_title and gender in employees dataset.
#Apply dummy enconding and find employees which are females.

In [8]:
employee = pd.read_csv('datos\\Employee_data.csv')
employee.head()
employee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49653 entries, 0 to 49652
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   EmployeeID           49653 non-null  int64
 1   recorddate_key       49653 non-null  object
 2   birthdate_key        49653 non-null  object
 3   orighiredate_key     49653 non-null  object
 4   terminationdate_key  49653 non-null  object
 5   age                  49653 non-null  int64
 6   length_of_service    49653 non-null  int64
 7   city_name            49653 non-null  object
 8   department_name      49653 non-null  object
 9   job_title            49653 non-null  object
 10  store_name           49653 non-null  int64
 11  gender_short         49653 non-null  object
 12  gender_full          49653 non-null  object
 13  termreason_desc      49653 non-null  object
 14  termtype_desc        49653 non-null  object
 15  STATUS_YEAR          49653 non-null  int64
 16  STATUS               49653 non-null  object
 17  BUSINESS_UNIT        49653 non-null  object
dtypes: int64(5), object(13)
memory usage: 6.8+ MB

In [9]:
employee.head()

,EmployeeID,recorddate_key,birthdate_key,orighiredate_key,terminationdate_key,age,length_of_service,city_name,department_name,job_title,store_name,gender_short,gender_full,termreason_desc,termtype_desc,STATUS_YEAR,STATUS,BUSINESS_UNIT
0,1318,12/31/2006 0:00,01/03/1954,8/28/1989,01/01/1900,52,17,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2006,ACTIVE,HEADOFFICE
1,1318,12/31/2007 0:00,01/03/1954,8/28/1989,01/01/1900,53,18,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2007,ACTIVE,HEADOFFICE
2,1318,12/31/2008 0:00,01/03/1954,8/28/1989,01/01/1900,54,19,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2008,ACTIVE,HEADOFFICE
3,1318,12/31/2009 0:00,01/03/1954,8/28/1989,01/01/1900,55,20,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2009,ACTIVE,HEADOFFICE
4,1318,12/31/2010 0:00,01/03/1954,8/28/1989,01/01/1900,56,21,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2010,ACTIVE,HEADOFFICE

In [11]:
ohe_employee = pd.get_dummies(employee,columns=["department_name"],prefix=["dn"],dtype=int)
ohe_employee.head()

,EmployeeID,recorddate_key,birthdate_key,orighiredate_key,terminationdate_key,age,length_of_service,city_name,job_title,store_name,...,dn_Information Technology,dn_Investment,dn_Labor Relations,dn_Legal,dn_Meats,dn_Processed Foods,dn_Produce,dn_Recruitment,dn_Store Management,dn_Training
0,1318,12/31/2006 0:00,01/03/1954,8/28/1989,01/01/1900,52,17,Vancouver,CEO,35,...,0,0,0,0,0,0,0,0,0,0
1,1318,12/31/2007 0:00,01/03/1954,8/28/1989,01/01/1900,53,18,Vancouver,CEO,35,...,0,0,0,0,0,0,0,0,0,0
2,1318,12/31/2008 0:00,01/03/1954,8/28/1989,01/01/1900,54,19,Vancouver,CEO,35,...,0,0,0,0,0,0,0,0,0,0
3,1318,12/31/2009 0:00,01/03/1954,8/28/1989,01/01/1900,55,20,Vancouver,CEO,35,...,0,0,0,0,0,0,0,0,0,0
4,1318,12/31/2010 0:00,01/03/1954,8/28/1989,01/01/1900,56,21,Vancouver,CEO,35,...,0,0,0,0,0,0,0,0,0,0

In [14]:
gender_encoding = pd.get_dummies(employee,columns=["gender_full"],prefix=["g"],dtype=int,drop_first=True)
gender_encoding.head()

,EmployeeID,recorddate_key,birthdate_key,orighiredate_key,terminationdate_key,age,length_of_service,city_name,department_name,job_title,store_name,gender_short,termreason_desc,termtype_desc,STATUS_YEAR,STATUS,BUSINESS_UNIT,g_Male
0,1318,12/31/2006 0:00,01/03/1954,8/28/1989,01/01/1900,52,17,Vancouver,Executive,CEO,35,M,Not Applicable,Not Applicable,2006,ACTIVE,HEADOFFICE,1
1,1318,12/31/2007 0:00,01/03/1954,8/28/1989,01/01/1900,53,18,Vancouver,Executive,CEO,35,M,Not Applicable,Not Applicable,2007,ACTIVE,HEADOFFICE,1
2,1318,12/31/2008 0:00,01/03/1954,8/28/1989,01/01/1900,54,19,Vancouver,Executive,CEO,35,M,Not Applicable,Not Applicable,2008,ACTIVE,HEADOFFICE,1
3,1318,12/31/2009 0:00,01/03/1954,8/28/1989,01/01/1900,55,20,Vancouver,Executive,CEO,35,M,Not Applicable,Not Applicable,2009,ACTIVE,HEADOFFICE,1
4,1318,12/31/2010 0:00,01/03/1954,8/28/1989,01/01/1900,56,21,Vancouver,Executive,CEO,35,M,Not Applicable,Not Applicable,2010,ACTIVE,HEADOFFICE,1

In [ ]:
female_count = len(employee) - gender_encoding['g_Male'].sum()
# len(gender_encoding[gender_encoding['g_Male']==0])
print(female_count, len(employee), gender_encoding['g_Male'].sum())
print(employee['gender_full'].value_counts())

25898 49653 23755
gender_full
Female    25898
Male      23755
Name: count, dtype: int64